### ISSUE TITLE
Possibly a bug in source code

### ISSUE THREAD

**Issue by juscodit** [garlik/4store#128]
Recently I read the code, and found the following line in function `node *node_ref(fs_ptree *pt, nodeid n)` of `src/backend/ptree.c`:

    uint32_t offset = n & 0x7ffffff;

I think maybe an `f` is missed, since in all other places, node offset is calculated with `n & 0x7fffffff`

rushan chen

**Comment by swh** [comment]
Good catch!

**Comment by swh** [comment]
Fixed in 6e2b4a70d4934484706a67b688ac30f3ca7baf98

**Comment by msalvadores** [comment]
Do backends need to reindex data with this code change?

**Comment by swh** [comment]
No, this function is used to map from node numbers in the mapped file to pointers in RAM, so it doesn't affect the on-disk structure.

**Comment by swh** [comment]
I've not tested the code change (don't have a live build at the moment), so it might cause bugs, but it doesn't look very likely.
