### ISSUE TITLE
for order clause strange output message 

### ISSUE THREAD

**Issue by andrewufrank** [garlik/4store#132]
for the query 
SELECT ?o ?count (count( ?o)  as ?count) WHERE { ?s     <http://auf.us.to/nlp2015:lemmaPoS>  ?o }  group by ?o ORDER by desc (?count) LIMIT 100
   >#EOQ
i get in the output a strange message "ordering?" - what should it indicate? the result is likey correct...

results.c:3103 ORDERING?
?o	?count
"Comma"@US	8742
"the:DT"@US	6979
"and:CC"@US	5450

**Comment by swh** [comment]
Ah, looks like someone left a debug line in there - removed in git HEAD.

**Comment by andrewufrank** [comment]
thank you!
