### ISSUE TITLE
HAVING clause

### ISSUE THREAD

**Issue by andrewufrank** [garlik/4store#142]
i have a query 
````
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dove: <http://gerastree.at/dove_2017#>

SELECT   ?filename ?md5 ?unit (count(?unit) as ?count) 
  WHERE {   ?unit  dove:md5  ?md5 .
            ?unit dove:filename ?filename
               }  
GROUP BY ?md5 
HAVING (count(?unit)> 1)
````
which gives exactly the same result as withou the HAVING clause (there are count 1 and 2 present in the result, with the HAVING clause, only count 2 should be included. 
is HAVING implemented? it would be very useful if the home page would list what is currently implemented and what not (e.g. subselect is not implemented, but this is only revealed when querying)

otherwise - thank you for maintaining a very simple to use sparql enpoint!
andrew

**Comment by swh** [comment]
I'm fairly sure that HAVING is not implemented, but it's such a long time ago, I'm not really sure.

**Comment by swh** [comment]
Yeah, just did a quick search of the source, there's no HAVING implementation.

Should throw a warning if you try to use unhandled keywords - it's a bit tricky though because the parser comes from a 3rd party.

**Comment by andrewufrank** [comment]
thank you for checking! i tried it on virtuoso, which i got to work .... (a very short description [http://andrewufrank.blogspot.co.at/](url) ). 
i still like 4store..
