### ISSUE TITLE
4s-dump Out of memory

### ISSUE THREAD

**Issue by goblin** [garlik/4store#96]
Trying to use 4s-dump on a large database resulted in Out of memory error. After a brief look it looks like the script tries to store the result of a massive SPARQL query in memory, which seems fundamentally wrong.

Documentation says I can back up via HTTP, but doesn't elaborate - is there a good way to do that?

**Comment by berezovskyi** [comment]
should this be closed then?

**Comment by swh** [comment]
I guess so
