### ISSUE TITLE
starting problems after last commit

### ISSUE THREAD

**Issue by rautenberg** [garlik/4store#97]
since https://github.com/garlik/4store/commit/392a3794d0bfec631bd690f623b3976eea8dc7df commit  (see https://github.com/garlik/4store/pull/95) our 4store refuses http connections. There is :
Dec 11 10:42:08 SERVERNAME 4store[26796]: 4s-server.c:471 kb=KBNAME runtime information file created
Dec 11 10:42:08 SERVERNAME 4store[26796]: 4s-server.c:581 4store backend v1.1.5-29-g3feefec for kb KBNAME on port 6734 (1 fds)
Dec 11 10:42:18 SERVERNAME 4store[27324]: httpd.c:1862 4store HTTP daemon v1.1.5-29-g3feefec started on host localhost port 9088
Dec 11 10:42:18 SERVERNAME 4store[27325]: 4s-client.c:144 kb=KBNAME connect to node <E2><80><9C>fe80::42e:47ff:fea1:9560%eth0<E2><80><9D> failed
Dec 11 10:42:18 SERVERNAME 4store[27325]: 4s-client.c:144 kb=KBNAME connect to node <E2><80><9C>2a01:4f8:150:6462::103<E2><80><9D> failed
Dec 11 10:42:18 SERVERNAME 4store[27325]: 4s-client.c:144 kb=KBNAME connect to node <E2><80><9C>10.0.0.107<E2><80><9D> failed
Dec 11 10:42:20 SERVERNAME 4store[27325]: 4s-client.c:309 kb=KBNAME waiting for lock on segment 0 on 10.0.0.103 port 6734
Dec 11 10:42:25 SERVERNAME 4store[27325]: 4s-client.c:309 kb=KBNAME waiting for lock on segment 0 on 10.0.0.103 port 6734
Dec 11 10:42:33 SERVERNAME 4store[27325]: 4s-client.c:309 kb=KBNAME waiting for lock on segment 0 on 10.0.0.103 port 6734
Dec 11 10:42:43 SERVERNAME 4store[27325]: 4s-client.c:309 kb=KBNAME waiting for lock on segment 0 on 10.0.0.103 port 6734
Dec 11 10:42:55 SERVERNAME 4store[27325]: 4s-client.c:309 kb=KBNAME waiting for lock on segment 0 on 10.0.0.103 port 6734
..... 
in the syslog file.  We do run a single 4store on an  virtual machine. 
10.0.0.107 is the correct IP (where 4s-client.c:144 try to connect) . There is no 10.0.0.103 at this machine.

**Comment by andrewufrank** [comment]
i just installed the 1.6.2 version from debian testing and it exhibits the same behaviour as discussed above. any chance that the fix got lost?

**Comment by andrewufrank** [comment]
it is only an error message (and perhaps a small time delay) - but the queries work. 
the error msg is : 
xx:~/Workspace9/text2onto/corenlp/grimm$ 4s-import grimm1 *.ttl
4store[21190]: 4s-client.c:144 kb=grimm1 connect to node “fexxxxx2:15ff:fe97:14eb%eth0” failed

**Comment by swh** [comment]
I think this is a different issue. 4store doesn't like IPV6 very much, try disabling it.
